### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by kokujin** [andrasq/node-prom-pushgateway#1]
I would like to know how to configure the cached metrics stored in the "config.data" folder. I found no information on this in the docs.

Thanks

Interesting module. Keep up with the good work!

**Comment by andrasq** [comment]
not sure what you're referring to -- `prom-pushgateway` doesn't use a `config.data` folder, it caches in memory the most recent seen values.  This internal cache can be clared with the server object's `clear()` method.

**Comment by andrasq** [comment]
Thanks for the good words!
